# Generated by Django 4.2.1 on 2023-06-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('gender', 'Male'), ('gender', 'Female')], max_length=128)),
            ],
        ),
    ]
